file_format: "1"
id: jiran_ble_lite
name: Jiran BLE Lite
url: https://github.com/ladniy/jiran-ble-lite
type: board
arch: arm
features:
  - keys
outputs:
  - usb
  - ble
siblings:
  - jiran_ble_lite_left
  - jiran_ble_lite_right
